/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UsersRouteImport } from './routes/users'
import { Route as SuppliersRouteImport } from './routes/suppliers'
import { Route as InventoryRouteImport } from './routes/inventory'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SuppliersIndexRouteImport } from './routes/suppliers.index'
import { Route as InventoryIndexRouteImport } from './routes/inventory.index'
import { Route as SuppliersRegisterRouteImport } from './routes/suppliers.register'
import { Route as SuppliersIdRouteImport } from './routes/suppliers.$id'
import { Route as InventoryRegisterRouteImport } from './routes/inventory.register'
import { Route as InventoryCatalogueRouteImport } from './routes/inventory.catalogue'
import { Route as SuppliersIdEditRouteImport } from './routes/suppliers.$id_.edit'
import { Route as InventoryEditIdRouteImport } from './routes/inventory.edit.$id'

const UsersRoute = UsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => rootRouteImport,
} as any)
const SuppliersRoute = SuppliersRouteImport.update({
  id: '/suppliers',
  path: '/suppliers',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryRoute = InventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SuppliersIndexRoute = SuppliersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SuppliersRoute,
} as any)
const InventoryIndexRoute = InventoryIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => InventoryRoute,
} as any)
const SuppliersRegisterRoute = SuppliersRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => SuppliersRoute,
} as any)
const SuppliersIdRoute = SuppliersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => SuppliersRoute,
} as any)
const InventoryRegisterRoute = InventoryRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => InventoryRoute,
} as any)
const InventoryCatalogueRoute = InventoryCatalogueRouteImport.update({
  id: '/catalogue',
  path: '/catalogue',
  getParentRoute: () => InventoryRoute,
} as any)
const SuppliersIdEditRoute = SuppliersIdEditRouteImport.update({
  id: '/$id_/edit',
  path: '/$id/edit',
  getParentRoute: () => SuppliersRoute,
} as any)
const InventoryEditIdRoute = InventoryEditIdRouteImport.update({
  id: '/edit/$id',
  path: '/edit/$id',
  getParentRoute: () => InventoryRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/inventory': typeof InventoryRouteWithChildren
  '/suppliers': typeof SuppliersRouteWithChildren
  '/users': typeof UsersRoute
  '/inventory/catalogue': typeof InventoryCatalogueRoute
  '/inventory/register': typeof InventoryRegisterRoute
  '/suppliers/$id': typeof SuppliersIdRoute
  '/suppliers/register': typeof SuppliersRegisterRoute
  '/inventory/': typeof InventoryIndexRoute
  '/suppliers/': typeof SuppliersIndexRoute
  '/inventory/edit/$id': typeof InventoryEditIdRoute
  '/suppliers/$id/edit': typeof SuppliersIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/users': typeof UsersRoute
  '/inventory/catalogue': typeof InventoryCatalogueRoute
  '/inventory/register': typeof InventoryRegisterRoute
  '/suppliers/$id': typeof SuppliersIdRoute
  '/suppliers/register': typeof SuppliersRegisterRoute
  '/inventory': typeof InventoryIndexRoute
  '/suppliers': typeof SuppliersIndexRoute
  '/inventory/edit/$id': typeof InventoryEditIdRoute
  '/suppliers/$id/edit': typeof SuppliersIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/inventory': typeof InventoryRouteWithChildren
  '/suppliers': typeof SuppliersRouteWithChildren
  '/users': typeof UsersRoute
  '/inventory/catalogue': typeof InventoryCatalogueRoute
  '/inventory/register': typeof InventoryRegisterRoute
  '/suppliers/$id': typeof SuppliersIdRoute
  '/suppliers/register': typeof SuppliersRegisterRoute
  '/inventory/': typeof InventoryIndexRoute
  '/suppliers/': typeof SuppliersIndexRoute
  '/inventory/edit/$id': typeof InventoryEditIdRoute
  '/suppliers/$id_/edit': typeof SuppliersIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/inventory'
    | '/suppliers'
    | '/users'
    | '/inventory/catalogue'
    | '/inventory/register'
    | '/suppliers/$id'
    | '/suppliers/register'
    | '/inventory/'
    | '/suppliers/'
    | '/inventory/edit/$id'
    | '/suppliers/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/users'
    | '/inventory/catalogue'
    | '/inventory/register'
    | '/suppliers/$id'
    | '/suppliers/register'
    | '/inventory'
    | '/suppliers'
    | '/inventory/edit/$id'
    | '/suppliers/$id/edit'
  id:
    | '__root__'
    | '/'
    | '/inventory'
    | '/suppliers'
    | '/users'
    | '/inventory/catalogue'
    | '/inventory/register'
    | '/suppliers/$id'
    | '/suppliers/register'
    | '/inventory/'
    | '/suppliers/'
    | '/inventory/edit/$id'
    | '/suppliers/$id_/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  InventoryRoute: typeof InventoryRouteWithChildren
  SuppliersRoute: typeof SuppliersRouteWithChildren
  UsersRoute: typeof UsersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/users': {
      id: '/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/suppliers': {
      id: '/suppliers'
      path: '/suppliers'
      fullPath: '/suppliers'
      preLoaderRoute: typeof SuppliersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory': {
      id: '/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof InventoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/suppliers/': {
      id: '/suppliers/'
      path: '/'
      fullPath: '/suppliers/'
      preLoaderRoute: typeof SuppliersIndexRouteImport
      parentRoute: typeof SuppliersRoute
    }
    '/inventory/': {
      id: '/inventory/'
      path: '/'
      fullPath: '/inventory/'
      preLoaderRoute: typeof InventoryIndexRouteImport
      parentRoute: typeof InventoryRoute
    }
    '/suppliers/register': {
      id: '/suppliers/register'
      path: '/register'
      fullPath: '/suppliers/register'
      preLoaderRoute: typeof SuppliersRegisterRouteImport
      parentRoute: typeof SuppliersRoute
    }
    '/suppliers/$id': {
      id: '/suppliers/$id'
      path: '/$id'
      fullPath: '/suppliers/$id'
      preLoaderRoute: typeof SuppliersIdRouteImport
      parentRoute: typeof SuppliersRoute
    }
    '/inventory/register': {
      id: '/inventory/register'
      path: '/register'
      fullPath: '/inventory/register'
      preLoaderRoute: typeof InventoryRegisterRouteImport
      parentRoute: typeof InventoryRoute
    }
    '/inventory/catalogue': {
      id: '/inventory/catalogue'
      path: '/catalogue'
      fullPath: '/inventory/catalogue'
      preLoaderRoute: typeof InventoryCatalogueRouteImport
      parentRoute: typeof InventoryRoute
    }
    '/suppliers/$id_/edit': {
      id: '/suppliers/$id_/edit'
      path: '/$id/edit'
      fullPath: '/suppliers/$id/edit'
      preLoaderRoute: typeof SuppliersIdEditRouteImport
      parentRoute: typeof SuppliersRoute
    }
    '/inventory/edit/$id': {
      id: '/inventory/edit/$id'
      path: '/edit/$id'
      fullPath: '/inventory/edit/$id'
      preLoaderRoute: typeof InventoryEditIdRouteImport
      parentRoute: typeof InventoryRoute
    }
  }
}

interface InventoryRouteChildren {
  InventoryCatalogueRoute: typeof InventoryCatalogueRoute
  InventoryRegisterRoute: typeof InventoryRegisterRoute
  InventoryIndexRoute: typeof InventoryIndexRoute
  InventoryEditIdRoute: typeof InventoryEditIdRoute
}

const InventoryRouteChildren: InventoryRouteChildren = {
  InventoryCatalogueRoute: InventoryCatalogueRoute,
  InventoryRegisterRoute: InventoryRegisterRoute,
  InventoryIndexRoute: InventoryIndexRoute,
  InventoryEditIdRoute: InventoryEditIdRoute,
}

const InventoryRouteWithChildren = InventoryRoute._addFileChildren(
  InventoryRouteChildren,
)

interface SuppliersRouteChildren {
  SuppliersIdRoute: typeof SuppliersIdRoute
  SuppliersRegisterRoute: typeof SuppliersRegisterRoute
  SuppliersIndexRoute: typeof SuppliersIndexRoute
  SuppliersIdEditRoute: typeof SuppliersIdEditRoute
}

const SuppliersRouteChildren: SuppliersRouteChildren = {
  SuppliersIdRoute: SuppliersIdRoute,
  SuppliersRegisterRoute: SuppliersRegisterRoute,
  SuppliersIndexRoute: SuppliersIndexRoute,
  SuppliersIdEditRoute: SuppliersIdEditRoute,
}

const SuppliersRouteWithChildren = SuppliersRoute._addFileChildren(
  SuppliersRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  InventoryRoute: InventoryRouteWithChildren,
  SuppliersRoute: SuppliersRouteWithChildren,
  UsersRoute: UsersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
